blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æ–‡æ¡£é—®é¢˜ Docs Issue
    url: https://github.com/NervJS/taro-docs/issues
    about: æ–‡æ¡£ç›¸å…³é—®é¢˜è¯·åœ¨è¿™é‡Œæäº¤
  - name: ğŸ“‘ åˆ›å»ºææ¡ˆ Proposal
    url: https://github.com/NervJS/taro/discussions/categories/rfc
    about: åˆ¶å®š Taro ä¸‹ä¸€æ­¥çš„æ›´æ–°è®¡åˆ’
  - name: ğŸ™‹ğŸ»â€â™‚ï¸ å‘èµ·æŠ•ç¥¨ Vote
    url: https://github.com/NervJS/taro/discussions/categories/polls
    about: æŠ•ç¥¨å†³å®š Taro çš„æœªæ¥
  - name: ğŸ™ŒğŸ¼ ç¤¾åŒºæ”¯æŒ General Question
    url: https://github.com/NervJS/taro/discussions/categories/q-a
    about: å‘å¸ƒä¸€èˆ¬æ€§é—®é¢˜
  - name: ğŸ— ç”Ÿæ€å»ºè®¾ Ecosystem
    url: https://github.com/NervJS/taro/discussions/categories/%E7%94%9F%E6%80%81
    about: å·¥å…·åº“ï¼Ÿç»„ä»¶åº“ï¼Ÿå¿«æ¥ä¸°å¯Œ Taro ç”Ÿæ€ï¼
